### ISSUE TITLE
Suggestion: vis-Style Structural Regular Expressions

### ISSUE THREAD

**Issue by ghost** [neurocyte/flow#11]
Well, I say _vis_-style, but really it was [Sam](https://github.com/martanne/vis/wiki/FAQ#what-are-structural-regular-expressions)'s idea first. vis is the only modal editor ever to grasp the concept with both hands and _not_ have the snail's pace selection-operator grammar; I wish I could use it but I need more code intelligence than it has. If Flow has it I'll never use anything else.

**Comment by neurocyte** [comment]
Can you be a bit more specific? Structural regex seems very vague to me and I don't really want to read the whole vis and sam manuals.

I intend to add regex support to the find command soon, which will also mean regex support for adding cursors and doing multi-cursor edits. I that enough regex support for you? (that's usually more than enough for me)

**Comment by welcome-linja** [comment]
A structural regular expression is a bit like a (CLI) pipe, except instead of running data through many commands, you’re running a selection through many filters. Like, you select the whole document, then you input a regex and every match of that regex becomes a different selection, then another regex and only the selections that contain that regex are kept, then another and every selection is split into multiple separated by those matches. It’s hard to explain in words; vis has a video demo on their README, and I’m sure there’s a command language section in the man page. It contains cursor-by-regex but goes far beyond it.

**Comment by neurocyte** [comment]
I don't see structural regexs as being likely in flow at the moment. So I'm going  to close this now. Perhaps if needs be open a discussion thread to discuss it more.
